### ISSUE TITLE
Where is the reference table to which keybind strings are valid?

### ISSUE THREAD

**Issue by thanhtacles** [saihon/focus-input-element#1]
Hi, I really like how simple and straightforward this chrome extenion is but it's crucially missing what keycode reference you're using. I figured it was a universal event.code js and tried ControlRight as right control, but it failed to recognize it. Perhaps a key selector map would be better, or a link to what table of key names you used?

**Comment by saihon** [comment]
This extension uses "[mousetrap](https://github.com/ccampbell/mousetrap)" internally. so it depends on the specification.
Does that mean there is a mistake in its implementation?

**Comment by thanhtacles** [comment]
Yeah I emailed the guy who made it and he says there is no discriminated
for left and right control or shift options

**Comment by saihon** [comment]
I understand a meaning but I don't know how to implement it.
If I specify shift+a, Mousetrap callback function's event.code value is KeyA.
How to can I get Shift event.code?

**Comment by thanhtacles** [comment]
https://keycode.info/ is really useful, albeit a bit different with mousetrap's implementation with its inability to discriminate between left and right.
It's just shift in mousetrap, which I suppose makes it easy.

**Comment by saihon** [comment]
Did you really read the code in that library?
I think it's not a bit, completely different.
