### ISSUE TITLE
Descriptions of Block: and Inline:. Two more shortcuts: top & bottom?

### ISSUE THREAD

**Issue by peter-kehl** [saihon/focus-input-element#25]
Thank you for Focus Input Element, Saihon.

Please
1. add description or examples of Block: and Inline:.
2. Many websites (like GitHub, GMail, Google, forums...) have a Search input at the top. It would be beneficial to have a dedicated shortcut for this purpose.
3. Some websites (mostly forums and GMail) have a Comment/Reply input at the bottom. Again, how about a dedicated shortcut for this, please?

**Comment by saihon** [comment]
It's been months since you opened the issue, but I've implemented your suggestions.
Thank you.
