### ISSUE TITLE
could option of "select all" be added?

### ISSUE THREAD

**Issue by furyNerd** [saihon/focus-input-element#27]
hi, thanks for keeping update this addon, could there be a option/feature of "select all" like 
https://addons.mozilla.org/en-us/firefox/addon/fox-input/
https://addons.mozilla.org/en-us/firefox/addon/cycle-input-focus-plus

i.e after focus to the element, the text gets auto selected, maybe:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

thanks for this addon :)

**Comment by saihon** [comment]
Hi @furyNerd
No such feature. not even as an option.
Do you need it?

**Comment by furyNerd** [comment]
> Hi @furyNerd No such feature. not even as an option. Do you need it?

hi, thanks for reply and yes, i think this could be a lot of help, in such cases:

within the search enigines, when i need to do a new search by focus back to the search text input, i do not need to delete(or stroke ctrl +a keys) the original words.

im not familiar with `.ts`, but by some study, according to 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

could this be done by adding
```
this.element.select();
```
after:

https://github.com/saihon/focus-input-element/blob/main/src/ts/focusableElement.ts#L9

**Comment by saihon** [comment]
Ok, I will add it. Thanks!
